### ISSUE TITLE
`is-executable` missing from `system/.function`

### ISSUE THREAD

**Issue by dgolant** [webpro/dotfiles#12]
I was struggling with my old fork of this repo, decided to pull master and fiddle. Doesn't seem like `is-executable` is defined anywhere in the code anymore. Commit history seems to indicate it used to be in `.function`

**Comment by webpro** [comment]
Ironically, it has become an executable in the /bin folder :-)

**Comment by dgolant** [comment]
Yes I literally just noticed that XD sorry

**Comment by dgolant** [comment]
Actually even if I run from bin, I get "command not found". Not an issue with the repo, but can you advise on why this happens? I am not storing the local repo in my home dir, FWIW.

**Comment by webpro** [comment]
The `bin` folder from this repo should be in your `PATH`.

**Comment by dgolant** [comment]
thanks!
