### ISSUE TITLE
Help wanted: Permission denied for dot files

### ISSUE THREAD

**Issue by kaspersoerensen** [webpro/dotfiles#14]
Hi there,

First off: this repo has been a huge help for me!

I have one problem though: Is there a way to make the scripts in the ``/bin`` folder executable without the need to do a ``chmod +x`` for the whole folder?

When I try to run for instance the ``dotfiles`` I get a ``permission denied``.

Running on Mac OS X 10.13.4. The folder is added to my ``PATH``

**Comment by webpro** [comment]
Hi, @kaspersoerensen. Sorry, just saw this issue. The files should be executable after cloning this repo with with Git. Haven't experienced the issue you described myself.

**Comment by kaspersoerensen** [comment]
Hi @webpro - I just tried to push an pull the executable to/from my own repo and it works, so I found out that there was no problem after all!
Thanks anyway! 😃
