### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by sauio** [webpro/dotfiles#15]
Hi, is it possible to do script for this settings? i search hard bud cant find

"Finder: items in the sidebar"
show Mac
hide iCloud/recents
defaults write com.apple.finder ShowRecentTags -bool false

"Settings-general-RecentItems - NONE"
"set F13(printScr) for save-screenshot-as-file"
"set Alt+F13(printScr) for save-pic-of-area-as-file"
"Mojave Settings-Update -ALL disable"

**Comment by webpro** [comment]
Sorry, I don't know how to script that.
