### ISSUE TITLE
source order of `system/*` breaks LS_COLOR

### ISSUE THREAD

**Issue by dropkick** [webpro/dotfiles#22]
I'm not sure of the _why_ just yet, but on both an existing and fresh install of macOS 10.14.1 (mojave) LS_COLORS doesn't work for me unless I move `system/.alias` to source earlier in `runcom/.bash_profile`

Updating the order on line 26 from
```function,function_*,path,env,alias,grep,prompt,nvm,completion,custom``` 
to
```function,function_*,alias,path,env,grep,prompt,nvm,completion,custom```
has LS_COLORS doing its thing again for me.

I'm not seeing any problems as a result of the change, but as I'm not sure of the cause I thought I should just post as an issue rather than a PR.

**Comment by webpro** [comment]
Hi, @dropkick! Thanks for the bug report.

I dug into this issue, and it ended up to be very subtle bug: recently I've moved some macos specific paths to a different file (9d3a9a42a1ef84cfe6ee62dbad450e12bf82e022), resulting in the wrong (stock) `ls` being used to test `ls --color`. It should be fixed now.
