### ISSUE TITLE
Update Homebrew Cask URL

### ISSUE THREAD

**Issue by reitermarkus** [webpro/dotfiles#23]
Hi, we just wanted to let you know that you are still linking to the old Homebrew Cask homepage (`caskroom.io`) in [`README.md`](https://github.com/webpro/dotfiles/blob/ba4fb907fb0c20d28126a604a8b67510152a4a46/README.md). This domain expired a few years ago and is not controlled by Homebrew anymore.

When you get a chance, please update the link to https://brew.sh/ or https://formulae.brew.sh/cask/.

Thank you,
the Homebrew team.

**Comment by webpro** [comment]
My apologies for not responding, @reitermarkus, not sure why I missed it. Now I ended up merging #24.
