### ISSUE TITLE
bats not installed

### ISSUE THREAD

**Issue by casxxi** [webpro/dotfiles#25]
Ubuntu 20.04 fresh install.
run dotfiles test:
línea 62: sub_bats: orden no encontrada
'bats' is not a known command or has errors.
Manually install bats, but maybe Makefile should install it?

**Comment by webpro** [comment]
It's in the Brewfile:

https://github.com/webpro/dotfiles/blob/master/install/Brewfile#L5

I don't fully understand how the `.PHONY` target works, but you need to install everything (`make` or `make all`) before running the tests (`make test`).
