### ISSUE TITLE
brew: no such file or directory

### ISSUE THREAD

**Issue by danepowell** [webpro/dotfiles#34]
When I follow the readme to install this repo on a fresh install of MacOS Sonoma (Macbook M1), I get the following error:

```
% make
sudo -v
while true; do sudo -n true; sleep 60; kill -0 "$" || exit; done 2>/dev/null &
is-executable brew || curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh | bash
if ! grep -q bash /private/etc/shells; then \
		brew install bash bash-completion@2 pcre && \
		sudo append bash /private/etc/shells && \
		chsh -s bash; \
	fi
brew install git git-extras
make: brew: No such file or directory
make: *** [git] Error 1
```

I'm having a heck of a time troubleshooting this because it makes no sense. If I change `brew` to `/opt/homebrew/bin/brew`, it works. If I print the `PATH` immediately before the Makefile calls brew, it shows `/opt/homebrew/bin` in the path. If I add `which brew` to the Makefile just before `brew`, _it correctly shows `/opt/homebrew/bin/brew`_. And yet... when the Makefile actually tries to run brew, you get `No such file or directory` 🤷

**Comment by webpro** [comment]
Oh no.. sorry about that. This has been a source of frustration for myself as well. Maybe it's because there's some "layering" in (sub) shells that's not obvious?

When I run `make` from my `.dotfiles` directory it has no issues finding `brew` 🤷

You could try to replace `brew` with `$(BIN)/brew` - if that works I'm happy to change it or accept a PR :)

**Comment by danepowell** [comment]
Here's a fix, though I can't say I'm fully satisfied with it: https://github.com/webpro/dotfiles/pull/35

**Comment by webpro** [comment]
At this point I'm honestly glad you went through this and fixed this in a very reasonable manner. Thank you so much! 🙏 

I'm going to do a clean install with Sonoma soon (after >2 years), let's see how it goes!
