### ISSUE TITLE
Typo in alias

### ISSUE THREAD

**Issue by andb0t** [webpro/dotfiles#9]
Hello,
first of all thanks for the nice introduction to dotfiles and posting your dotilfes code open source!

Second of all, I found a [line which I think is not correct](https://github.com/webpro/dotfiles/blob/master/system/.alias#L29). Are you sure about overwriting your `pull` alias? Seems like a dangerous bug:

```shell
alias push="git push"
alias pull="git pull"
alias pull="git push --force"
```
Cheers!

**Comment by webpro** [comment]
Thanks for the catch, @andb0t! I notice I don't even really use these aliases at all, so I've removed them right away.
